# Generated by Django 5.0.6 on 2024-07-16 12:34

import django.db.models.deletion
import uploadreports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='name',
        ),
        migrations.AddField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(default=uploadreports.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reports',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
