# Generated by Django 5.0.6 on 2024-07-16 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreports', '0002_remove_reports_name_reports_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
