# Generated by Django 5.0.6 on 2024-07-16 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreports', '0003_reports_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='extracted_text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='text_vector',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=1536),
        ),
    ]
