# Generated by Django 5.0.6 on 2024-07-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadreports', '0004_reports_extracted_text_reports_text_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
